version: '3'
services:
  app:
    image: 'backend:latest'
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=p@stgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 9999:8080
  db:
    image: postgres:10.4
    container_name: db
    volumes:
      - /var/db/data/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p@stgres
    ports:
      - 5432:5432